### ISSUE TITLE
clean column

### ISSUE THREAD

**Issue by arademaker** [odanoburu/conllu-mode#20]
to implement a function to clean all the values of the current column (replacing with `-`).

**Comment by odanoburu** [comment]
just for documentation purposes, what's the use case for this? do annotators regularly have to clear columns in order to revise them, or is it something else?

**Comment by arademaker** [comment]
Indeed, that was a good question and it makes me conclude that I don't have a strong use case, just a particular demand for cleaning the XPOSTAG field. But I don't think it justifies this feature in the mode.
