### ISSUE TITLE
default values for flycheck

### ISSUE THREAD

**Issue by arademaker** [odanoburu/conllu-mode#37]
You wrote:

> note that the validate.py demands a two-letter language code to do its validation; conllu-mode tries to infer this from the file name, assuming it follows UD filename convention of starting with such a language code (as in pt_bosque-ud-test.conllu). if your file doesn’t start with a language code, conllu-mode will ask you for a language code; if you don’t supply anything, Flycheck will invoke the validate script with the default value of ud.

Could we have variables to supply default values for:

1. validate vs no validate
2. language

So when I open a file with conllu extension, I would not have to answer any question?

**Comment by odanoburu** [comment]
these already existed, but had problems (see commit message if interested)

I put an example in the README, I'd set them up as directory local variables if I were you.

**Comment by arademaker** [comment]
Even with the `.dir-locals.el` in the directory, opening a conllu file ask for validation and the language.

**Comment by arademaker** [comment]
sorry, once more, I forgot to update the package! ;-)
